POST http://localhost:3000/createUser HTTP/1.1
Content-Type: application/json;

{
    "name": "John",
    "email": "test@example.com",
    "password": "Test password",
    "gender":"male",
    "age":"30",
}